const ALLOWED_BACKGROUND_OVERLAY_KINDS = new Set([
  "code-overlay",
  "raster-overlay"
]);

const MAX_BACKGROUND_CANDIDATES = 6;
const MAX_BACKGROUND_OVERLAYS = 48;
const MIN_BACKGROUND_SIZE = 24;
const MIN_OVERLAY_SIZE = 4;

module.exports = {
  ALLOWED_BACKGROUND_OVERLAY_KINDS,
  MAX_BACKGROUND_CANDIDATES,
  MAX_BACKGROUND_OVERLAYS,
  MIN_BACKGROUND_SIZE,
  MIN_OVERLAY_SIZE
};

